version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_USER: devuser
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data:delegated
    restart: always
volumes:
  db-volume:
